model:
  name: UNet
  in_channels: 4
  out_channels: 1 
  dimensions: 3     # 3D UNet
  channels: [32, 64, 128, 256, 512]
  strides: [2, 2, 2, 2]  #down sampling strides
  num_res_units: 2
  norm: batch
  dropout: 0.2
  act: relu